schemaVersion: '1'
id: overseerr
name:
  en: Overseerr
  fr: Overseerr
description:
  en: Overseerr is a free and open source software application for managing requests for your media library. It integrates with your existing services, such as Sonarr, Radarr, and Plex!
  fr: Overseerr est une application logicielle gratuite et open source pour la gestion des demandes de votre bibliothèque multimédia. Il s'intègre à vos services existants, tels que Sonarr, Radarr et Plex !
version: 1.35.0
architectures:
- amd64
- arm64
containers:
- name: overseerr
  image: linuxserver/overseerr:1.35.0@sha256:6108ed066d4a919c05251d9dab041c1e55e67ff7247e7b31be97b65ffcbaeeb1
  environment:
    PUID: '1000'
    PGID: '1000'
    TZ: Etc/UTC
  ports:
  - container: 5055
    protocol: tcp
    proxy: true
  volumes:
  - name: config
    target: /config
    type: app
resources:
  memoryMinimum: 256M
  memoryRecommended: 512M
  cpuRecommended: 1
secrets: []
permissions:
  privileged: false
  hostNetwork: false
  capabilities: []
  devices: []
backup:
  mode: crash-consistent
  paths:
  - /config
migrations: []
releaseNotes:
  en: Overseerr 1.35.0 includes bug fixes for notifications, web push resubscription, Plex Watchlist URL handling, availability sync, request state updates, and specials handling. - The release also updates Docker build support, including py3-setuptools for arm builds on Node 20. - The linuxserver/overseerr:1.35.0 Docker image tag was published on 2026-02-16.
  fr: Overseerr 1.35.0 includes bug fixes for notifications, web push resubscription, Plex Watchlist URL handling, availability sync, request state updates, and specials handling. - The release also updates Docker build support, including py3-setuptools for arm builds on Node 20. - The linuxserver/overseerr:1.35.0 Docker image tag was published on 2026-02-16.
securityClassification: standard
