schemaVersion: '1'
id: foldingathome
name:
  en: Foldingathome
  fr: Foldingathome
description:
  en: '[Folding@home] is a distributed computing project for simulating protein dynamics, including the process of protein folding and the movements of proteins implicated in a variety of diseases. It brings together citizen scientists who volunteer to run…'
  fr: Application auto-hébergée de calcul scientifique pour votre serveur Menhir.
icon: https://api.iconify.design/mdi:molecule.svg?color=%238b5cf6
version: 8.5.6-ls209
architectures:
- amd64
- arm64
containers:
- name: foldingathome
  image: lscr.io/linuxserver/foldingathome:latest@sha256:4c0a6ee7821ce938d91a6a7d4d004f3e1f93f6be324d2f40ac841d9dcfa819f8
  ports:
  - container: 7396
    protocol: tcp
    proxy: true
  volumes:
  - name: config
    target: /config
    type: app
resources:
  memoryMinimum: 512M
  memoryRecommended: 1G
  cpuRecommended: 2
secrets: []
permissions:
  privileged: false
  hostNetwork: false
  capabilities: []
  devices: []
backup:
  mode: crash-consistent
  paths:
  - /config
migrations: []
releaseNotes:
  en: Menhir integration for Foldingathome 8.5.6-ls209.
  fr: Intégration Menhir pour Foldingathome 8.5.6-ls209.
securityClassification: standard
