schemaVersion: '1'
id: diskover
name:
  en: Diskover
  fr: Diskover
description:
  en: diskover is an open source file system indexer that uses Elasticsearch to index and manage data across heterogeneous storage systems.
  fr: Application auto-hébergée de analyse du stockage pour votre serveur Menhir.
version: v2.3.5-ls241
architectures:
- amd64
- arm64
containers:
- name: diskover
  image: lscr.io/linuxserver/diskover:latest@sha256:e1c2d74c804227841b8e639129f969ffe65c2fd2be7dcf7b4e93f1e2de91290e
  ports:
  - container: 80
    protocol: tcp
    proxy: true
  volumes:
  - name: config
    target: /config
    type: app
  - name: data
    target: /data
    type: share
resources:
  memoryMinimum: 256M
  memoryRecommended: 512M
  cpuRecommended: 1
secrets: []
permissions:
  privileged: false
  hostNetwork: false
  capabilities: []
  devices: []
backup:
  mode: crash-consistent
  paths:
  - /config
migrations: []
releaseNotes:
  en: Menhir integration for Diskover v2.3.5-ls241.
  fr: Intégration Menhir pour Diskover v2.3.5-ls241.
securityClassification: standard
