schemaVersion: '1'
id: transmission
name:
  en: Transmission
  fr: Transmission
description:
  en: 'transmission is designed for easy, powerful use. Transmission has the features you want from a BitTorrent client: encryption, a web interface, peer exchange, magnet links, DHT, µTP, UPnP and NAT-PMP port forwarding, webseed support, watch directories,…'
  fr: Application auto-hébergée de gestion des téléchargements pour votre serveur Menhir.
icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Transmission/icon.svg
version: 4.1.3-r0-ls355
architectures:
- amd64
- arm64
containers:
- name: transmission
  image: lscr.io/linuxserver/transmission:latest@sha256:6b78970a0cb00709d3817fcb47b7cf74da56a43384bbd50d03955ca87e38c5f0
  ports:
  - container: 9091
    protocol: tcp
    proxy: true
  - container: 51413
    protocol: tcp
    proxy: false
  - container: 51413
    protocol: udp
    proxy: false
  volumes:
  - name: config
    target: /config
    type: app
  - name: downloads
    target: /downloads
    type: share
  - name: watch
    target: /watch
    type: share
resources:
  memoryMinimum: 256M
  memoryRecommended: 512M
  cpuRecommended: 1
secrets: []
permissions:
  privileged: false
  hostNetwork: false
  capabilities: []
  devices: []
backup:
  mode: crash-consistent
  paths:
  - /config
migrations: []
releaseNotes:
  en: Menhir integration for Transmission 4.1.3-r0-ls355.
  fr: Intégration Menhir pour Transmission 4.1.3-r0-ls355.
securityClassification: standard
