schemaVersion: '1'
id: thunderbird
name:
  en: Thunderbird
  fr: Thunderbird
description:
  en: '[Thunderbird] is a free and open-source personal information manager primarily used as an e-mail client with a calendar and contactbook, as well as an RSS feed reader, chat client, and news client.'
  fr: Application auto-hébergée de courrier électronique pour votre serveur Menhir.
version: 1140.12.1build1-0ubuntu0.24.04.1mt1-ls44
architectures:
- amd64
- arm64
containers:
- name: thunderbird
  image: lscr.io/linuxserver/thunderbird:latest@sha256:9b64e3d46b0fb34a8fae57f2c28b29f849b158bdde78e288771315da5b61d3ab
  ports:
  - container: 3000
    protocol: tcp
    proxy: true
  - container: 3001
    protocol: tcp
    proxy: false
  volumes:
  - name: config
    target: /config
    type: app
resources:
  memoryMinimum: 256M
  memoryRecommended: 512M
  cpuRecommended: 1
secrets: []
permissions:
  privileged: false
  hostNetwork: false
  capabilities: []
  devices: []
backup:
  mode: crash-consistent
  paths:
  - /config
migrations: []
releaseNotes:
  en: Menhir integration for Thunderbird 1140.12.1build1-0ubuntu0.24.04.1mt1-ls44.
  fr: Intégration Menhir pour Thunderbird 1140.12.1build1-0ubuntu0.24.04.1mt1-ls44.
securityClassification: sensitive
