schemaVersion: '1'
id: remmina
name:
  en: Remmina
  fr: Remmina
description:
  en: '[Remmina] is a remote desktop client written in GTK, aiming to be useful for system administrators and travellers, who need to work with lots of remote computers in front of either large or tiny screens. Remmina supports multiple network protocols, in an…'
  fr: Application auto-hébergée de bureau à distance pour votre serveur Menhir.
version: 1.4.40dfsg-2ubuntu1-ls222
architectures:
- amd64
- arm64
containers:
- name: remmina
  image: lscr.io/linuxserver/remmina:latest@sha256:a2934f90fa450d9176c60492a634eb4c13a9d1c057c4e0ca64222bea7f8bd781
  ports:
  - container: 3000
    protocol: tcp
    proxy: true
  - container: 3001
    protocol: tcp
    proxy: false
  volumes:
  - name: config
    target: /config
    type: app
resources:
  memoryMinimum: 1G
  memoryRecommended: 2G
  cpuRecommended: 2
secrets: []
permissions:
  privileged: false
  hostNetwork: false
  capabilities: []
  devices: []
backup:
  mode: crash-consistent
  paths:
  - /config
migrations: []
releaseNotes:
  en: Menhir integration for Remmina 1.4.40dfsg-2ubuntu1-ls222.
  fr: Intégration Menhir pour Remmina 1.4.40dfsg-2ubuntu1-ls222.
securityClassification: standard
