schemaVersion: '1'
id: wallabag
name:
  en: Wallabag
  fr: Wallabag
description:
  en: Wallabag is a web page saving app that allows users to save articles for offline reading, extracting content for a distraction-free experience. Its intuitive Web interface enables saving articles with a click, ensuring users can read them at their convenience. The app's core features include convenient web page saving, optimized reading, and flexible content organization. It extracts only the article's content, removing pop-ups and ads, and displays it in a clean, comfortable view. Users can organize saved…
  fr: Wallabag est une application de sauvegarde de pages web qui permet aux utilisateurs de sauvegarder des articles pour une lecture hors ligne, en extrayant le contenu pour une expérience sans distraction. Son interface web intuitive permet de sauvegarder des articles d'un clic, garantissant aux utilisateurs de pouvoir les lire à leur convenance. Les fonctionnalités principales de l'application incluent la sauvegarde pratique de pages web, la lecture optimisée et l'organisation flexible du contenu. Elle extrait…
version: 2.6.14
architectures:
- amd64
- arm64
containers:
- name: wallabag
  image: wallabag/wallabag:2.6.14@sha256:4a527e027e0d59e87c14225ef11e005af3d4890374202ad319ce5e63dfc66709
  environment:
    SYMFONY__ENV__DOMAIN_NAME: http://<IP>:25661
    SYMFONY__ENV__SERVER_NAME: Wallabag
  ports:
  - container: 80
    protocol: tcp
    proxy: true
  volumes:
  - name: images
    target: /var/www/wallabag/web/assets/images
    type: app
  healthcheck:
    test:
    - CMD
    - wget
    - --no-verbose
    - --tries=1
    - --spider
    - http://localhost/api/info
    interval: 1m
    timeout: 3s
    retries: 3
resources:
  memoryMinimum: 512M
  memoryRecommended: 1G
  cpuRecommended: 1
secrets: []
permissions:
  privileged: false
  hostNetwork: false
  capabilities: []
  devices: []
backup:
  mode: crash-consistent
  paths:
  - /var/www/wallabag/web/assets/images
migrations: []
releaseNotes:
  en: 2.6.14 adds an annotations filter to the entries API endpoint. - Fixes include deprecations, the Docker base image, reading-time computation for short entries, storing many URLs through the API, and dependency updates. - The wallabag/wallabag:2.6.14 Docker image tag was published on 2025-10-07.
  fr: 2.6.14 adds an annotations filter to the entries API endpoint. - Fixes include deprecations, the Docker base image, reading-time computation for short entries, storing many URLs through the API, and dependency updates. - The wallabag/wallabag:2.6.14 Docker image tag was published on 2025-10-07.
securityClassification: standard
