schemaVersion: '1'
id: psitransfer
name:
  en: PsiTransfer
  fr: PsiTransfer
description:
  en: 'PsiTransfer is a simple, self-hosted open-source file sharing service that allows you to share files securely and easily without registration. Key Features: - No Registration Required: Share files instantly without creating an account. - Privacy and Control: All files are stored on your own server, giving you complete control over your data. - Password Protection: Protect shared files with a password for enhanced security. - Upload Expiry: Set uploaded files to automatically expire after a specific time to save…'
  fr: 'PsiTransfer est un service simple de partage de fichiers open source auto-hébergé qui vous permet de partager des fichiers de manière sécurisée et facile sans inscription. Fonctionnalités principales : - Aucune inscription requise : Partagez des fichiers instantanément sans créer de compte. - Confidentialité et contrôle : Tous les fichiers sont stockés sur votre propre serveur, vous donnant un contrôle total sur vos données. - Protection par mot de passe : Protégez les fichiers partagés avec un mot de passe pour…'
version: 2.4.1
architectures:
- amd64
- arm64
containers:
- name: psitransfer
  image: psitrax/psitransfer:v2.4.1@sha256:8fc64c1cac1142a0fc0b6be3874e96bd2a65385c5e0622eb91d3c599bcf35fa8
  environment:
    PSITRANSFER_ADMIN_PASS: secret
  ports:
  - container: 3000
    protocol: tcp
    proxy: true
  volumes:
  - name: data
    target: /data
    type: app
resources:
  memoryMinimum: 256M
  memoryRecommended: 512M
  cpuRecommended: 1
secrets: []
permissions:
  privileged: false
  hostNetwork: false
  capabilities: []
  devices: []
backup:
  mode: crash-consistent
  paths:
  - /data
migrations: []
releaseNotes:
  en: v2.4.1 includes security fixes and should be updated. - UTF-8 support was added for content disposition in file downloads. - Dependencies and changelog generation were updated.
  fr: v2.4.1 inclut des correctifs de sécurité et doit être mis à jour. - La prise en charge UTF-8 a été ajoutée pour le content disposition des téléchargements de fichiers. - Les dépendances et la génération du changelog ont été mises à jour.
securityClassification: standard
