schemaVersion: '1'
id: apprise-api
name:
  en: Apprise API
  fr: Apprise API
description:
  en: apprise-api Takes advantage of Apprise through your network with a user-friendly API. * Send notifications to more than 100 services. * An incredibly lightweight gateway to Apprise. * A production ready micro-service at your disposal. * A Simple Website to…
  fr: Application auto-hébergée de surveillance et diagnostic pour votre serveur Menhir.
version: v1.5.1-ls252
architectures:
- amd64
- arm64
containers:
- name: apprise-api
  image: lscr.io/linuxserver/apprise-api:latest@sha256:80b939b0a0a80e6ae85a855fd2e0283b02c70f3bc6ad24a333fb9c2ebc0fa8ee
  ports:
  - container: 8000
    protocol: tcp
    proxy: true
  volumes:
  - name: config
    target: /config
    type: app
  - name: attachments
    target: /attachments
    type: share
resources:
  memoryMinimum: 256M
  memoryRecommended: 512M
  cpuRecommended: 1
secrets: []
permissions:
  privileged: false
  hostNetwork: false
  capabilities: []
  devices: []
backup:
  mode: crash-consistent
  paths:
  - /config
migrations: []
releaseNotes:
  en: Menhir integration for Apprise API v1.5.1-ls252.
  fr: Intégration Menhir pour Apprise API v1.5.1-ls252.
securityClassification: standard
