schemaVersion: '1'
id: nzbget
name:
  en: NZBGet
  fr: NZBGet
description:
  en: nzbget is a usenet downloader, written in C++ and designed with performance in mind to achieve maximum download speed by using very little system resources.
  fr: Application auto-hébergée de gestion des téléchargements pour votre serveur Menhir.
icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Nzbget/icon.svg
version: v26.2-ls255
architectures:
- amd64
- arm64
containers:
- name: nzbget
  image: lscr.io/linuxserver/nzbget:latest@sha256:d79a67d21cf63431d9e08e7f10c920ef1f68f06e61c015e602c2c3f79d28a0ac
  ports:
  - container: 6789
    protocol: tcp
    proxy: true
  volumes:
  - name: config
    target: /config
    type: app
  - name: downloads
    target: /downloads
    type: share
resources:
  memoryMinimum: 256M
  memoryRecommended: 512M
  cpuRecommended: 1
secrets: []
permissions:
  privileged: false
  hostNetwork: false
  capabilities: []
  devices: []
backup:
  mode: crash-consistent
  paths:
  - /config
migrations: []
releaseNotes:
  en: Menhir integration for NZBGet v26.2-ls255.
  fr: Intégration Menhir pour NZBGet v26.2-ls255.
securityClassification: standard
